# title: Shivani Sahu
# description: Data Science Portfolio Website
# ğŸ“ Location: Boston, MA  
# ğŸ“± Mobile: (+1) 857-390-4920  
# ğŸ“§ Email: sahu.shi@northeastern.edu  
# ğŸ”— LinkedIn: [LinkedIn](https://www.linkedin.com/in/shivani-sahu)  
# logo: /Whitagram-Image.jpeg
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Shivani Sahu
description: "ğŸ“ Location: Boston, MA                               ğŸ“± Mobile: (+1) 857-390-4920                              ğŸ“§ Email: sahu.shi@northeastern.edu                     ğŸ”— LinkedIn: https://www.linkedin.com/in/shivani-sahu"
location: Boston, MA  
mobile: (+1) 857-390-4920  
email: sahu.shi@northeastern.edu  
linkedin_url: https://www.linkedin.com/in/shivani-sahu
logo: /Whitagram-Image.jpeg
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme # Add other plugins here if needed
